### PR TITLE
Add board span, fixes dash-16

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/8)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcOLv-yDyvY9yRaJcCC:-KcOLv-yDyvY9yRaJcCD:bcraf66) (no related file):*
> board-cols=2

shouldn't the attribute value always be ="value" between brackets?

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcOLz9qSvTrxtZHgkpF:-KcOLz9qSvTrxtZHgkpG:b-j97hoz) (no related file):*
```
<vaadin-board-row>
    <div class="top a">one</div>
    <div class="top b">two</div>
    <div class="top c">three</div>
</vaadin-board-row>
```

behaves incorrectly in tablet size

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcOMHA6H1XdslqB2isE:-KcOMHA6H1XdslqB2isF:b9t2qo1) (no related file):*
```
        <vaadin-board-row>
          <div board-cols="2" class="top a">one</div>
          <div board-cols="2" class="top b">two</div>
          <div board-cols="3" class="top c">three</div>
        </vaadin-board-row>
```

should ignore the attributes and shouldn't drop elements

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcOMTcBzkWcmDV1y_AB:-KcOMTcBzkWcmDV1y_AC:but2m46) (no related file):*
is it possible to only drop elements from the slot? would it make sense to only do it there?

---

*[vaadin-board-row.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcNk9IHfjrZI-xSMgwM:-KcNk9IILj6hvJJug4eQ:b-xkgkh0) ([raw file](https://github.com/vaadin/vaadin-board/blob/24e6f8e7fb07422236029229f08beb4352106336/vaadin-board-row.html#L61)):*
>         let config = nodeSpans.reduce((a,b)=>{return a+"-"+b});

looks like reinventing array.join but it's not technically wrong
>         let error ="The column configuration "+config+" is not valid; column count should add up to 3 or 4.";

I think this could mention the board-cols attribute

---

*[test/vaadin-board_boardcols_test.html, line 121 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcNllrUooZvbt5H8pOl:-KcNllrUooZvbt5H8pOm:b-196j7s) ([raw file](https://github.com/vaadin/vaadin-board/blob/24e6f8e7fb07422236029229f08beb4352106336/test/vaadin-board_boardcols_test.html#L121)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>              let oldWarn =console.warn;
>              console.warn = function(message) {
>                warnMessage = message;
>              }
>              console.warnd = oldWarn;
</details>

should this be undone in a tear-down stage? If no then first and last lines are not needed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/8)*

**Comment by rogozinds** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcOLv-yDyvY9yRaJcCC:-KcRkh54mUWhrC7hyy9b:b-o9fc9q) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> board-cols=2

shouldn't the attribute value always be ="value" between brackets?
</blockquote></details>

At least it was so in Polymer1, let's keep this convention.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcOLz9qSvTrxtZHgkpF:-KcS1M61jPM_8EOM6TD0:be47tlf) (no related file):*
> <vaadin-board-row>
>     <div class="top a">one</div>
>     <div class="top b">two</div>
>     <div class="top c">three</div>
> </vaadin-board-row>
Done

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcOMHA6H1XdslqB2isE:-KcSCtuSnlDoIiHGnGI-:b369gvz) (no related file):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>         <vaadin-board-row>
>           <div board-cols="2" class="top a">one</div>
>           <div board-cols="2" class="top b">two</div>
>           <div board-cols="3" class="top c">three</div>
>         </vaadin-board-row>
</details>
Done

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcOMTcBzkWcmDV1y_AB:-KcSMTfOMOIVti1q_hsz:b-gdtjze) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

is it possible to only drop elements from the slot? would it make sense to only do it there?
</blockquote></details>

Create a DASH-40 ticket about it. For now leave as it is.

---

*[vaadin-board-row.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcNk9IHfjrZI-xSMgwM:-KcSDq5tLGqbd2Dz7XXC:byvb6qy) ([raw file](https://github.com/vaadin/vaadin-board/blob/24e6f8e7fb07422236029229f08beb4352106336/vaadin-board-row.html#L61)):*
> let error ="The column configuration "+config+" is not valid; column count should add up to 3 or 4.";
> 
> 
> I think this could mention the board-cols attribute
Decided to remove config

---

*[test/vaadin-board_boardcols_test.html, line 121 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcNllrUooZvbt5H8pOl:-KcSHz7A_V3TwWyzHFE6:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-board/blob/24e6f8e7fb07422236029229f08beb4352106336/test/vaadin-board_boardcols_test.html#L121)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>              let oldWarn =console.warn;
>              console.warn = function(message) {
>                warnMessage = message;
>              }
>              console.warnd = oldWarn;

should this be undone in a tear-down stage? If no then first and last lines are not needed
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/8)*

**Comment by alvarezguille** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcTNnH_nrNuX-S99kY8:-KcTNnH_nrNuX-S99kY9:bkd7xrw) (no related file):*
vaadin-board_boardcols_test.html should be added to test/index.html

---

*[vaadin-board-row.html, line 47 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcTNAYGgs-xNLPBZ_Dy:-KcTNAYH2-qTVe4rEBhA:boswqbx) ([raw file](https://github.com/vaadin/vaadin-board/blob/5f57766c92f06acbb496c9917d73199af3ac54e5/vaadin-board-row.html#L47)):*
> @param{nodesCount}

@param{Number} as the previous?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/8)*

**Comment by rogozinds** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcTNnH_nrNuX-S99kY8:-KcTQ5SYoSXYyGjcCLQR:bb6un1j) (no related file):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

vaadin-board_boardcols_test.html should be added to test/index.html
</blockquote></details>

Done

---

*[vaadin-board-row.html, line 47 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board/8#-KcTNAYGgs-xNLPBZ_Dy:-KcTPN7L0r8m4ebiIduL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/5f57766c92f06acbb496c9917d73199af3ac54e5/vaadin-board-row.html#L47)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> @param{nodesCount}

@param{Number} as the previous?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/8)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/8)*

**Pull request merged**
