### PR TITLE
Adding changes to the LightDOM triggers relayout.

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/9)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Will review this after board span changes are final

**Comment by alvarezguille** [comment]
vaadin-board_light_dom_test.html should be in test/index.html

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-board_light_dom_test.html, line 91 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/9#-KcbOGnsuvDjC3pn8Hl_:-KcbOGnsuvDjC3pn8Hla:b-adb3fu) ([raw file](https://github.com/vaadin/vaadin-board/blob/1c8c9c282b3cb294544bd018a07506631602c1be/test/vaadin-board_light_dom_test.html#L91)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>         test('Changing styling of the board and calling resize triggers relayouting', function() {
>           var row = fixture('board-row-4-items');
>           row.style.width="700px";
>           row.redraw();
</details>
>  
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>
>           var rowRect = row.getBoundingClientRect();
>           var children = row.querySelectorAll("div");
>           for (let i = 0; i < children.length; i++) {
>             var rect = children[i].getBoundingClientRect();
</details>
>  
>             assert.approximately(rect.left, (i%2 * rowRect.width / 2)+rowRect.left, 1);
>             assert.approximately(rect.top, (Math.floor(i/2) * rowRect.height / 2)+rowRect.top,1);
>           }

Is this test case light dom related?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/9#-:-Kcbd_jAweJIDX_zgHjY:b-n78am2)*

**Comment by alvarezguille** [comment]
Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/9)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-board_light_dom_test.html, line 91 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/9#-KcbOGnsuvDjC3pn8Hl_:-Kcc76YFtGhoDA3__lOI:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/1c8c9c282b3cb294544bd018a07506631602c1be/test/vaadin-board_light_dom_test.html#L91)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         test('Changing styling of the board and calling resize triggers relayouting', function() {
>           var row = fixture('board-row-4-items');
>           row.style.width="700px";
>           row.redraw();
>  
>           var rowRect = row.getBoundingClientRect();
>           var children = row.querySelectorAll("div");
>           for (let i = 0; i < children.length; i++) {
>             var rect = children[i].getBoundingClientRect();
>  
>             assert.approximately(rect.left, (i%2 * rowRect.width / 2)+rowRect.left, 1);
>             assert.approximately(rect.top, (Math.floor(i/2) * rowRect.height / 2)+rowRect.top,1);
>           }

Is this test case light dom related?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/9)*

**Pull request merged**
