### PR TITLE
Add elements definition to Vaadin namespace

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/62)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/62#-KnnP4IedYIDo75B36bK:-KnnP4IedYIDo75B36bL:b-gihmaj) (no related file):*
Need to resolve conflicts with master.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/62)*

**Comment by alvarezguille** [comment]
*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-board/62#-KnnP4IedYIDo75B36bK:-KnnTAm2obnZ1H8JiPU1:bb7f2mf) (no related file):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Need to resolve conflicts with master.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/62)*

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/62#-:-Knna9zq3bQ6x_sb4UAM:bnfp4nl)*

**Comment by DiegoCardoso** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/62)*

**Comment by DiegoCardoso** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/62)*

**Pull request merged**
