### PR TITLE
Include a static getter for the element version

### PR DESCRIPTION
**Pull request by Artur-**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/77)

### CODE REVIEW

**Comment by tulioag** [comment]
if I do the following commands, an error is generated:
```bash
$ npm install
[...]
$ npm version 1.1.0-beta2

> vaadin-board@1.1.0-beta2 preversion /home/tulio/projects/vaadin-board
> gulp version:update

[09:09:02] Using gulpfile ~/projects/vaadin-board/gulpfile.js
[09:09:02] Starting 'version:check'...
[09:09:02] Tested 1 tests, 1 passes, 0 failures: PASS
[09:09:02] Finished 'version:check' after 80 ms
[09:09:02] Starting 'version:update'...
[09:09:02]  
[09:09:02] Finished 'version:update' after 17 ms
v1.1.0-beta2
npm ERR! code 1
npm ERR! Command failed: git add /home/tulio/projects/vaadin-board/package-lock.json
npm ERR! The following paths are ignored by one of your .gitignore files:
npm ERR! package-lock.json
npm ERR! Use -f if you really want to add them.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tulio/.npm/_logs/2017-12-19T07_09_02_310Z-debug.log

```

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/77#-:-L0hanhwwrG4HXfi_f0r:b6imruo)*

**Comment by Artur-** [comment]
Does it work without `package-lock.json` in gitignore? That's not really relevant to this change, it was only made at the same time for all the core elements

**Comment by tulioag** [comment]
Yes. It also works if you create a .npmrc file containing
```
package-lock=false
```
Then npm will not create the package-lock.json

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/77#-:-L0hlPSJ3bOxD93_aDUG:b-xpaen)*

**Comment by Artur-** [comment]
Added `.npmrc`

---

Review status: 4 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/77#-:-L0if56JpjSgtViEwX1q:bdxve53)*

**Comment by tulioag** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/77#-:-L0mvBeGwxfZg_Vb_z1A:bnfp4nl)*

**Pull request merged**
