### PR TITLE
Add class names for different width of the row, fixes DASH-43

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/16)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-board-row.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/16#-KdAz6JS59RcOcSka_Sz:-KdAz6JS59RcOcSka_T-:b-b10x3v) ([raw file](https://github.com/vaadin/vaadin-board/blob/abfa2c1312b0c2568c4878f4cdf021c288da612e/vaadin-board-row.html#L17)):*
> ```HTML
>         box-sizing: border-box;
>         flex-grow: 1;
>         flex-shrink: 1;
> ```

Is this related?

---

*[vaadin-board-row.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/16#-KdAzBEX0lAAqWf_L1TS:-KdAzBEX0lAAqWf_L1TT:bng7664) ([raw file](https://github.com/vaadin/vaadin-board/blob/abfa2c1312b0c2568c4878f4cdf021c288da612e/vaadin-board-row.html#L36)):*
>         this._SMALL_VIEWPORT_CLASSNAME = "col-sm";
>         this._MEDIUM_VIEWPORT_CLASSNAME = "col-md";
>         this._BIG_VIEWPORT_CLASSNAME = "col-lg";

Is this the decided API?

---

*[vaadin-board-row.html, line 190 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/16#-KdAzQjLE1u9QZ59AUFT:-KdAzQjLE1u9QZ59AUFU:b-jr6d1h) ([raw file](https://github.com/vaadin/vaadin-board/blob/abfa2c1312b0c2568c4878f4cdf021c288da612e/vaadin-board-row.html#L190)):*
> this._addStyleNames(e, width);

was the idea to add style name to the slots or to the row?

---

*[test/index.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/16#-KdAzk_BgYhy0a0Wv98S:-KdAzk_BgYhy0a0Wv98T:bm8uapq) ([raw file](https://github.com/vaadin/vaadin-board/blob/abfa2c1312b0c2568c4878f4cdf021c288da612e/test/index.html#L22)):*
>         'vaadin-board_test.html',
>         'vaadin-board_style.html'

can we keep this in alphabetical order?
it's easier to see if and which test file is missing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/16)*

**Comment by rogozinds** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-board-row.html, line 17 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/16#-KdAz6JS59RcOcSka_Sz:-KdB1pW16qW03v38aPC8:b-7srse0) ([raw file](https://github.com/vaadin/vaadin-board/blob/abfa2c1312b0c2568c4878f4cdf021c288da612e/vaadin-board-row.html#L17)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

Is this related?
</blockquote></details>

no. Removed

---

*[vaadin-board-row.html, line 36 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/16#-KdAzBEX0lAAqWf_L1TS:-KdB1kA8PdsIRD7B19aK:b-q537vb) ([raw file](https://github.com/vaadin/vaadin-board/blob/abfa2c1312b0c2568c4878f4cdf021c288da612e/vaadin-board-row.html#L36)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         this._SMALL_VIEWPORT_CLASSNAME = "col-sm";
>         this._MEDIUM_VIEWPORT_CLASSNAME = "col-md";
>         this._BIG_VIEWPORT_CLASSNAME = "col-lg";

Is this the decided API?
</blockquote></details>

No, that's just my proposal, this is how it's down in bootstrap.

---

*[vaadin-board-row.html, line 190 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/16#-KdAzQjLE1u9QZ59AUFT:-KdB6BIXTPksMZ-yh1o_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/abfa2c1312b0c2568c4878f4cdf021c288da612e/vaadin-board-row.html#L190)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> this._addStyleNames(e, width);

was the idea to add style name to the slots or to the row?
</blockquote></details>

Done.

---

*[test/index.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/16#-KdAzk_BgYhy0a0Wv98S:-KdB6ILkZm-XUehV7dTO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/abfa2c1312b0c2568c4878f4cdf021c288da612e/test/index.html#L22)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>         'vaadin-board_test.html',
>         'vaadin-board_style.html'

can we keep this in alphabetical order?
it's easier to see if and which test file is missing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/16)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/16)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/16)*

**Pull request merged**
