### PR TITLE
Fix dom repeat, fixes #60

### LINKED ISSUE #60: Dom-repeat does not work properly inside vaadin-board-row
Dom-repeat does not work properly inside vaadin-board-row. When adding items to the board via dom-repeat, dom-repeat is counted as a child element of the road so you can not add for elements via dom-repeat only 3 or less.

Here is the complete example:
```
<link rel="import" href="../../polymer/polymer-element.html">
<link rel="import" href="../vaadin-board.html">
<dom-module id="board-element">
  <template>
    <style>
    </style>
    <vaadin-board>
        <vaadin-board-row>
          <dom-repeat items="{{items}}">
            <template>
              <div>{{item}}</div>
            </template>
          </dom-repeat>
        </vaadin-board-row>
    </vaadin-board>

  </template>

  <script>
    class BoardElement extends Polymer.Element {
      static get is() {
        return 'board-element';
      }

      static get properties() {
        return {
          items: {
            type: Array,
            value: ["Foo", "Bar", "Faz", "Foo"]
          }
        }
      }

    }
    customElements.define(BoardElement.is, BoardElement);
  </script>
</dom-module>
```

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/64)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-board-template_test.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/64#-KnoAUxltf8uUHdzDEHy:-KnoAUxltf8uUHdzDEHz:b-xfm4zp) ([raw file](https://github.com/vaadin/vaadin-board/blob/2bf6f4a58d7f4cc86b6e163125dfa6052644309a/test/vaadin-board-template_test.html#L49)):*
> var children = row.querySelectorAll("div");

needed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/64)*

**Comment by alvarezguille** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-board-row.html, line 180 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/64#-KnoAdLxHv2_5fBwyruQ:-KnoAdLxHv2_5fBwyruR:b9f4e8l) ([raw file](https://github.com/vaadin/vaadin-board/blob/2bf6f4a58d7f4cc86b6e163125dfa6052644309a/vaadin-board-row.html#L180)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>
>           const isElementNode = function(node) {
>             return !((node.nodeType === node.TEXT_NODE)
>             || (node instanceof Polymer.DomRepeat)
>             || (node instanceof Polymer.DomIf));
>           }
>           const filteredNodes = nodes.filter(isElementNode);
</details>

indentation for this block seems wrong

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/64)*

**Comment by DiegoCardoso** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[test/vaadin-board-template_test.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/64#-KnoAUxltf8uUHdzDEHy:-Knrs4rpjM4KwKx2LHHj:bo5767u) ([raw file](https://github.com/vaadin/vaadin-board/blob/2bf6f4a58d7f4cc86b6e163125dfa6052644309a/test/vaadin-board-template_test.html#L49)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> var children = row.querySelectorAll("div");

needed?
</blockquote></details>

Also, `row` is undefined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/64)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/64)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-board-row.html, line 180 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/64#-KnoAdLxHv2_5fBwyruQ:-KnrwJDawFAffTwBEhuB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/2bf6f4a58d7f4cc86b6e163125dfa6052644309a/vaadin-board-row.html#L180)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>           const isElementNode = function(node) {
>             return !((node.nodeType === node.TEXT_NODE)
>             || (node instanceof Polymer.DomRepeat)
>             || (node instanceof Polymer.DomIf));
>           }
>           const filteredNodes = nodes.filter(isElementNode);

indentation for this block seems wrong
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/64)*

**Comment by rogozinds** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-board-template_test.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/64#-KnoAUxltf8uUHdzDEHy:-Kns-97dKPTQfgNCZmxL:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/2bf6f4a58d7f4cc86b6e163125dfa6052644309a/test/vaadin-board-template_test.html#L49)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Also, `row` is undefined.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/64)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/64)*

**Pull request merged**
