### PR TITLE
Add test that WC has something in local DOM, closes DASH-10.

### PR DESCRIPTION
**Pull request by rogozinds**
Add tests for IPad and Safari10.
Exclude IE11 and Safari9 from tests, because it's not supporting ES6.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/3)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Reviewed 4 of 5 files at r1.
Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/3)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/3#-KbPsFqwRNwDILCYgEPA:-KbPsFqxgUIVKtE1NS-O:bj0c7gi) ([raw file](https://github.com/vaadin/vaadin-board/blob/5869cb5d07c508a12c8a6e8d05c2482ea548e161/demo/index.html#L12)):*
>     <link rel="import" href="../../iron-demo-helpers/demo-pages-shared-styles.html">
>     <link rel="import" href="../../iron-demo-helpers/demo-snippet.html">
It's not relevant to the PR but since file is already included, the imports are both failing an unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/3)*

**Comment by rogozinds** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/index.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/3#-KbPsFqwRNwDILCYgEPA:-KbQ0fLOiucZiJVV9nLk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/5869cb5d07c508a12c8a6e8d05c2482ea548e161/demo/index.html#L12)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>     <link rel="import" href="../../iron-demo-helpers/demo-pages-shared-styles.html">
>     <link rel="import" href="../../iron-demo-helpers/demo-snippet.html">
It's not relevant to the PR but since file is already included, the imports are both failing an unused
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/3)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/3)*

**Pull request merged**
