### PR TITLE
Merge P3 preview to master

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/107)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[bower.json, line 9 at r5](https://reviewable.io/reviews/vaadin/vaadin-board/107#-LG5Z30a4H-winRu6lir:-LG5Z30b3X9Xy_yZ5aDm:b-p18i12) ([raw file](https://github.com/vaadin/vaadin-board/blob/105cf4576391f7e196e455df8d155ab41f85c4c0/bower.json#L9)):*
> ```JSON
>     "polymer": "^2.0.0",
>     "iron-resizable-behavior": "^2.0.0",
>     "vaadin-license-checker": "vaadin/license-checker#p3-preview",
> ```

v2.1.0-alpha1

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/107)*

**Comment by manolo** [comment]
Review status: 0 of 23 files reviewed, 1 unresolved discussion (waiting on @manolo)

---

*[bower.json, line 9 at r5](https://reviewable.io/reviews/vaadin/vaadin-board/107#-LG5Z30a4H-winRu6lir:-LG5a2Kg9Hcsg78macyC:b-9tqbd3) ([raw file](https://github.com/vaadin/vaadin-board/blob/105cf4576391f7e196e455df8d155ab41f85c4c0/bower.json#L9)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

v2.1.0-alpha1
</blockquote></details>

my script skip this because the repo is misnamed `vaadin/license-checker` instead of `vaadin/vaadin-license-checker` 

Done

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/107)*

**Comment by alexberazouski** [comment]
Reviewed 16 of 21 files at r1, 1 of 1 files at r2, 1 of 4 files at r3, 4 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed, 2 unresolved discussions (waiting on @tomivirkki and @manolo)

---

*[demo/index.html, line 17 at r6](https://reviewable.io/reviews/vaadin/vaadin-board/107#-LGOvNbfARouxdVBLqJC:-LGOvNbgEiWWG4bqI4pZ:b5tmjzy) ([raw file](https://github.com/vaadin/vaadin-board/blob/a86040a2c73bcef2bd9d93d209c1960a4af96694/demo/index.html#L17)):*
> ```HTML
> 
>   <link rel="import" href="../vaadin-board.html">
>   <link rel="import" href="../vaadin-board-row.html">
> ```

Do we need this extra import here?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/107)*

**Comment by manolo** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @tomivirkki and @manolo)

---

*[demo/index.html, line 17 at r6](https://reviewable.io/reviews/vaadin/vaadin-board/107#-LGOvNbfARouxdVBLqJC:-LGR2u1T70dWzoOl22i5:b4jr8s4) ([raw file](https://github.com/vaadin/vaadin-board/blob/a86040a2c73bcef2bd9d93d209c1960a4af96694/demo/index.html#L17)):*
<details><summary><i>Previously, alexberazouski wrote…</i></summary><blockquote>

Do we need this extra import here?
</blockquote></details>

board-row is used in all demos, so it should be imported somewhere.  Anyways this line was added by @platosha any strong reason for keeping or removing it ? 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/107)*

**Review by alvarezguille — APPROVED** [review]
> Reviewed 2 of 2 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/107)* status: all files reviewed, 1 unresolved discussion (waiting on @tomivirkki)

**Review by alvarezguille — APPROVED** [review]
> Dismissed @tomivirkki from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/107)* status: all files reviewed, 1 unresolved discussion

**Review by alvarezguille — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/107)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
