### PR TITLE
Add file to verify possible alignment and overflow configurations

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/32)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/demo-element.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/32#-KgK0xPcpreJr9PAjcQn:-KgK0xPcpreJr9PAjcQo:brw4736) ([raw file](https://github.com/vaadin/vaadin-board/blob/2a0d05a09f585f89bc7d7aec161213414cd81e63/demo/demo-element.html#L32)):*
>     <div class="number">[[itemNumber]]</div>
Looks like it's more a caption, than a number. 
At least this "<demo-element item-number="scroll"
Doesn't look like  a number.

,Better change to caption, both classname and property name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/32)*

**Comment by rogozinds** [comment]
One small comment, not critical, just makes it a bit more readable.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/32#-:-KgK1MLRNmxqZW9Q9qy8:b-ltt6d6)*

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/demo-element.html, line 32 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/32#-KgK0xPcpreJr9PAjcQn:-KgK5DJw4JfC3FFUD1vb:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/2a0d05a09f585f89bc7d7aec161213414cd81e63/demo/demo-element.html#L32)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>     <div class="number">[[itemNumber]]</div>
Looks like it's more a caption, than a number. 
At least this "<demo-element item-number="scroll"
Doesn't look like  a number.

,Better change to caption, both classname and property name
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/32)*

**Comment by rogozinds** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/32)*

**Pull request merged**
