### PR TITLE
Update polymer version

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/57)

### CODE REVIEW

**Comment by alvarezguille** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/57#-KkLbOov2huPI-_CzT5x:-KkLbOowG0IhhiGh_5Hw:b-bv3n1c) ([raw file](https://github.com/vaadin/vaadin-board/blob/0c4df8a3a201e8b2d1ea9c35d9dd536ac5f065a7/bower.json#L14)):*
> ```JSON
>     "app-layout": "PolymerElements/app-layout#v2.0.0",
>     "web-component-tester": "^4.0.0",
>     "webcomponentsjs": "^1.0.0-rc.11",
> ```

this should be stable version

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Comment by rogozinds** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/57#-KkLbOov2huPI-_CzT5x:-Kkj9doLlvS75IdmefL9:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/0c4df8a3a201e8b2d1ea9c35d9dd536ac5f065a7/bower.json#L14)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

this should be stable version
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Comment by rogozinds** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/57#-KkLbOov2huPI-_CzT5x:-KkjB7xuSsUIkbT6iX9G:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/0c4df8a3a201e8b2d1ea9c35d9dd536ac5f065a7/bower.json#L14)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Comment by alvarezguille** [comment]
*[test/vaadin-board_media-queries.html, line 53 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-board/57#-KktC6cH4r7TlGRYYT6X:-KktC6cH4r7TlGRYYT6Y:bxim1p8) ([raw file](https://github.com/vaadin/vaadin-board/blob/44aec25395d6ecbc8392959f78652d4f10d94e37/test/vaadin-board_media-queries.html#L53)):*
>           done();

should be inside else

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Comment by alvarezguille** [comment]
Reviewed 3 of 4 files at r4.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Comment by rogozinds** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/vaadin-board_media-queries.html, line 53 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-board/57#-KktC6cH4r7TlGRYYT6X:-KktCYBL1MHJzrLXGx_C:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/44aec25395d6ecbc8392959f78652d4f10d94e37/test/vaadin-board_media-queries.html#L53)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

>           done();

should be inside else
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Comment by alvarezguille** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/57)*

**Pull request merged**
