### PR TITLE
Fix bug with slots

### PR DESCRIPTION
**Pull request by rogozinds**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/61)

### CODE REVIEW

**Comment by alvarezguille** [comment]
*[test/vaadin-board_slot_test.html, line 63 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-Knj8u_kDHbllHf8xNmE:-Knj8u_kDHbllHf8xNmF:bvywd51) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/vaadin-board_slot_test.html#L63)):*
> Elements insdie board that have slots are not children of board.

There is a typo, and it's a bit confusing IMHO

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61)*

**Comment by DiegoCardoso** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[test/board-element.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-Knmj7x5gnTbkzdli628:-Knmj7x6HHWNF0pqxzvO:bhb3n9q) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/board-element.html#L8)):*
>  :host {
>  
>             }

It seems that this empty block is making build fails: `block-no-empty ` and `rule-empty-line-before` rules.

---

*[test/outer.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-KnmjWqyAF1itZ1-UEul:-KnmjWqyAF1itZ1-UEum:b-pn4k0x) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/outer.html#L8)):*
> ```HTML
>             :host {
>                 border-width: 3px;
>                 border-style:solid;
> ```

Build failing. Need to add a space after `:` because of `declaration-colon-space-after` rule.

---

*[test/vaadin-board_slot_test.html, line 58 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-KnmjmVVsqjDbpr4IOgK:-KnmjmVVsqjDbpr4IOgL:b-njz8rb) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/vaadin-board_slot_test.html#L58)):*
> ```HTML
>             var child = children[i];
> 
>             assert.isAtLeast(child.getAttribute("style").indexOf("flex-basis: 25%"), 0,
> ```

This test is failing on my machine because `flex-basis` is `50%`.  Would it be because viewport is not large enough?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61)*

**Comment by rogozinds** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/outer.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-KnmjWqyAF1itZ1-UEul:-Knn-bqg4hsnsxTt4Bdn:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/outer.html#L8)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

Build failing. Need to add a space after `:` because of `declaration-colon-space-after` rule.
</blockquote></details>

Done.

---

*[test/vaadin-board_slot_test.html, line 63 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-Knj8u_kDHbllHf8xNmE:-Knn0vnRwjHhp8w6jtku:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/vaadin-board_slot_test.html#L63)):*
<details><summary><i>Previously, alvarezguille (Guille) wrote…</i></summary><blockquote>

> Elements insdie board that have slots are not children of board.

There is a typo, and it's a bit confusing IMHO
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61)*

**Comment by rogozinds** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/board-element.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-Knmj7x5gnTbkzdli628:-Knn13G_RN3a9D3h5VgJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/board-element.html#L8)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

>  :host {
>  
>             }

It seems that this empty block is making build fails: `block-no-empty ` and `rule-empty-line-before` rules.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61)*

**Comment by rogozinds** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[test/vaadin-board_slot_test.html, line 58 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-KnmjmVVsqjDbpr4IOgK:-Knn1VQrqsUBZZKErDth:b-nzyilq) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/vaadin-board_slot_test.html#L58)):*
<details><summary><i>Previously, DiegoCardoso (Diego Cardoso) wrote…</i></summary><blockquote>

This test is failing on my machine because `flex-basis` is `50%`.  Would it be because viewport is not large enough?
</blockquote></details>

Added fixed size of the board.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61)*

**Comment by rogozinds** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/vaadin-board_slot_test.html, line 58 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-KnmjmVVsqjDbpr4IOgK:-Knn2bR90LEkFCYbqGlO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/5fc11f46ec17d58b408f4517cfe2e70fdb1690a9/test/vaadin-board_slot_test.html#L58)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Added fixed size of the board.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61)*

**Comment by alvarezguille** [comment]
Reviewed 4 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61)*

**Comment by alvarezguille** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-:-KnnGgKPezgpq5px7RQz:bnfp4nl)*

**Comment by DiegoCardoso** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/61#-:-KnnHNSp5uJy-7gDvmsM:bnfp4nl)*

**Pull request merged**
