### PR TITLE
Reimplment vaadin-board-row with CSS grid

### PR DESCRIPTION
**Pull request by Peppe**
Reimplemented `vaadin-board-row` with CSS Grid instead of Flex layout. It gives easier support for adding gutters and the layout probably won't break by adding paddings and whatnot to items.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/73)

### CODE REVIEW

**Comment by DiegoCardoso** [comment]
We are currently using Firefox 50 in our tests. However, the first version to support CSS Grid is Firefox 52, as you can see in the pic below:

CSS Grid support

So, in order to make tests green, we should probably remove support for older version than 52. I have downloaded the 52 version from there version page and ran the tests locally to verify and the tests are passing.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/73#-:-KtuEipMGWD4d-MrpbDm:b-66avir)*

**Comment by DiegoCardoso** [comment]
Sorry, [this is the actual link](https://ftp.mozilla.org/pub/firefox/releases/52.0/mac/en-US/).

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/73#-:-KtuG5YCEU66GWzTawpP:b-abgq28)*

**Comment by DiegoCardoso** [comment]
Just notice that the test are also failing for Chrome 55 and the stable version of CSS Grid was released at Chrome 57.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/73#-:-KtuhOKfWxcr9e9FDcqG:bhqgvzp)*

**Comment by Peppe** [comment]
Oh, so it is that reason why the tests are failing. I tested on two computers where tests passed on Chrome and it confused me why they were failing on Saucelabs.

**Comment by DiegoCardoso** [comment]
After updating FF and Chrome, tests are green for both browsers, but it's still failing for Safari. As you can see on the previous pic, CSS Grid was only introduced for Safari 10.1 for macOS and Safari 10.3 for iOS. 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/73#-:-Ktvb8Pd45oOLgbtXZpu:blp9g52)*

**Comment by johannesh2** [comment]
This PR is still missing support for IE11, but that could be added later if we decided to take this change in. However, Safari 9 does not have support for CSS grid and we are supporting it still in V10/11.

**Comment by lkraav** [comment]
@johannesh2 Safari 9 isn't polyfillable?

**Comment by johannesh2** [comment]
My understanding is that CSS Grid polyfill does not exist. One option would be to use the worse version for Safari 9 and support better version for the browsers. What do you think @alvarezguille?

**Comment by lkraav** [comment]
1. how about doing a `@supports` flexbox fallback or, alternatively, CSS grid as progressive enhancement?

2. What about the general quality of this PR? If we don't care about back-compatibility, is this PR determined to be production quality work to run off a fork, until Vaadin 12 perhaps catches up?

**Comment by alvarezguille** [comment]
Seems like moving the base implementation to css grid and keeping flex based solution for safari 9 could be a good approach to move the product forward.
I'll arrange some prototyping on this

@lkraav regarding
> is this PR determined to be production quality work

The PR needs to be rebased at least, but apart from that do you have any concern or found some issue?

**Comment by lkraav** [comment]
> The PR needs to be rebased at least, but apart from that do you have any concern or found some issue?

I don't know yet. There's limited time for experimentation with this right now. I'll give it a shot and get back to you here.

**Comment by lkraav** [comment]
Working on rebase now.

**Comment by alvarezguille** [comment]
Included in #117, discussion will continue there

**Pull request closed without merging**
