### PR TITLE
Implement basic column case with resizable mixin class

### PR DESCRIPTION
**Pull request by alvarezguille**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-board/7)

### CODE REVIEW

**Comment by rogozinds** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-board-row.html, line 57 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-KbxoPSyss8TE3OwjydT:-KbxoPSyss8TE3OwjydU:b-ujyd89) ([raw file](https://github.com/vaadin/vaadin-board/blob/001d838e9c59197b7340554a75a70fdda7a0de39/vaadin-board-row.html#L57)):*
> ```HTML
>           const filteredNodes = nodes.filter(node => node.nodeType !== node.TEXT_NODE);
>           var newFlexBasis = '25%';
>           if (width < 600) {
> ```

Can we specify this as some class constants?
So we can change them later easily ( Iguess they should be changed)(?

---

*[test/vaadin-board_test.html, line 31 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-Kbxp5PYSMnoLqapxTPP:-Kbxp5PYSMnoLqapxTPQ:bcnoh6u) ([raw file](https://github.com/vaadin/vaadin-board/blob/a2db727d9c4bd3629a4bdc6b52d2305aaf284d04/test/vaadin-board_test.html#L31)):*
> ```HTML
>       suite('vaadin-board', function () {
> 
>         test('Four items take 25% each on Desktop.', function () {
> ```

The idea was that we add same tests for Tablet and Mobile size displays. Here you can use constants defined for resizing.
So something like
Desktop assert.approximately(rect.left, i * parentWidth / 4, 10);

Tablet assert.approximately(rect.left, 0 * parentWidth / 4, 10);
Tablet assert.approximately(rect.left, 1 * parentWidth / 4, 10);
Tablet assert.approximately(rect.left, 0 * parentWidth / 4, 10);
Tablet assert.approximately(rect.left, 1 * parentWidth / 4, 10);

Mobile assert.approximately(rect.left, 0, 10);

And something similar for height

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/7)*

**Comment by rogozinds** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[test/vaadin-board_test.html, line 36 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-KbxyniGgP1uMJdfMTIj:-KbxyniHnzOdZpt0FF9w:b-6c4i2z) ([raw file](https://github.com/vaadin/vaadin-board/blob/c255ec99f938d7cdc6e63c278883ddb8e27d180f/test/vaadin-board_test.html#L36)):*
> 1
I guess that's just a typo?

---

*[test/vaadin-board_test.html, line 72 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-Kbxz9mNvBUaCLBdtCAx:-Kbxz9mOEGum2d8EeKL5:b-amept4) ([raw file](https://github.com/vaadin/vaadin-board/blob/c255ec99f938d7cdc6e63c278883ddb8e27d180f/test/vaadin-board_test.html#L72)):*
>     assert.equal(rect.left, (i%2 * rowRect.width / 2)+rowRect.left);
>             assert.equal(rect.top, (Math.floor(i/2) * rowRect.height / 2)+rowRect.top);
I would use assert.approximatelly, because there are some issues when running tests in the cloud.
Well If there are no issues right now, we can use strict comparesion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/7)*

**Comment by alvarezguille** [comment]
Review status: 4 of 6 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-board-row.html, line 57 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-KbxoPSyss8TE3OwjydT:-Kby3VvrI30_1T4Qz2Nw:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/001d838e9c59197b7340554a75a70fdda7a0de39/vaadin-board-row.html#L57)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

Can we specify this as some class constants?
So we can change them later easily ( Iguess they should be changed)(?
</blockquote></details>

Done.

---

*[test/vaadin-board_test.html, line 31 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-Kbxp5PYSMnoLqapxTPP:-Kby-63ynq5OyTWrQlOM:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/a2db727d9c4bd3629a4bdc6b52d2305aaf284d04/test/vaadin-board_test.html#L31)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

The idea was that we add same tests for Tablet and Mobile size displays. Here you can use constants defined for resizing.
So something like
Desktop assert.approximately(rect.left, i * parentWidth / 4, 10);

Tablet assert.approximately(rect.left, 0 * parentWidth / 4, 10);
Tablet assert.approximately(rect.left, 1 * parentWidth / 4, 10);
Tablet assert.approximately(rect.left, 0 * parentWidth / 4, 10);
Tablet assert.approximately(rect.left, 1 * parentWidth / 4, 10);

Mobile assert.approximately(rect.left, 0, 10);

And something similar for height
</blockquote></details>

Done.

---

*[test/vaadin-board_test.html, line 36 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-KbxyniGgP1uMJdfMTIj:-Kby-4jg3rcb4dILgKxR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/c255ec99f938d7cdc6e63c278883ddb8e27d180f/test/vaadin-board_test.html#L36)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

> 1
I guess that's just a typo?

</blockquote></details>

Done.

---

*[test/vaadin-board_test.html, line 72 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-Kbxz9mNvBUaCLBdtCAx:-Kby-FHrxbjnyz11vM2k:b-vfm1s4) ([raw file](https://github.com/vaadin/vaadin-board/blob/c255ec99f938d7cdc6e63c278883ddb8e27d180f/test/vaadin-board_test.html#L72)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>     assert.equal(rect.left, (i%2 * rowRect.width / 2)+rowRect.left);
>             assert.equal(rect.top, (Math.floor(i/2) * rowRect.height / 2)+rowRect.top);
I would use assert.approximatelly, because there are some issues when running tests in the cloud.
Well If there are no issues right now, we can use strict comparesion.
</blockquote></details>

I think the difference is that before it wasn't considering the row top, or left depending on the  assertion

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/7)*

**Comment by rogozinds** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-board-row.html, line 30 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-Kby7lTJa5WAlNYpgciU:-Kby7lTJa5WAlNYpgciV:b-cctp0y) ([raw file](https://github.com/vaadin/vaadin-board/blob/a406cbf11801abd8f4f3bd99ba8cc84a84ecb6e4/vaadin-board-row.html#L30)):*
>         this._oneColumnMaxWidth = 600;
>         this._twoColumnsMaxWidth = 1000;
Can you make it upper case as it's a constant? I don't know how to define constants in ES6, but at least naming it will help
_ONE_COLUMN_MAX_WIDTH
_TWO_COLUMNS_MAX_WIDTH

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/7)*

**Comment by alvarezguille** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-board-row.html, line 30 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-Kby7lTJa5WAlNYpgciU:-Kby9L7K9z4_meV1_YyW:b-896fix) ([raw file](https://github.com/vaadin/vaadin-board/blob/a406cbf11801abd8f4f3bd99ba8cc84a84ecb6e4/vaadin-board-row.html#L30)):*
<details><summary><i>Previously, rogozinds (rogozinds) wrote…</i></summary><blockquote>

>         this._oneColumnMaxWidth = 600;
>         this._twoColumnsMaxWidth = 1000;
Can you make it upper case as it's a constant? I don't know how to define constants in ES6, but at least naming it will help
_ONE_COLUMN_MAX_WIDTH
_TWO_COLUMNS_MAX_WIDTH
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/7)*

**Comment by rogozinds** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-board/7#-:-Kby9v8z18WlDUrmLcSO:bnfp4nl)*

**Pull request merged**
